name: CI

on:
  - push
  - pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Ruby
        uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop
