name: CI

on:
  - push
  - pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop
