name: CI

on:
  - push
  - pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop
